gpu_id: '2'
data_root: '/data1/liulei_lab/Data'
data_path_CAVE: '/data1/liulei_lab/Data/CAVE_512_28/'
data_path_KAIST: '/data1/liulei_lab/Data/KAIST_CVPR2021/'
mask_path: '/data1/liulei_lab/Data/TSA_real_data/mask.mat'
outf: '/data1/liulei_lab/MODEL_file/Fourier/20230214/real'
re_path: None
RESUME: False
input_setting: 'H'
input_mask: 'Mask'
size: 384
epoch_sam_num: 5000
seed: 1
batch_size: 1
isTrain: True
max_epoch: 300
scheduler: 'CosineAnnealingLR'
loss_type: L2
milestones: [50,100,150,200,250]
gamma: 0.5
learning_rate: 6.0e-4
